spring:
  application:
    name: recommendation-service

  datasource:
    url: ${POSTGRES_URI}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
    instance:
      preferIpAddress: true

